help:
	@echo "That App idea Tools Guide";
	@echo "";
	@echo "initalize - Example of how to initialize a stack   ";
	@echo "initalize - Example of how to initialize a stack   ";

initialize:
	initialize-stack -r eu-west-1 --external-domain-name thisapp-lab.itcant.be --internal-domain-name thisapp-lab --profile wakaru --project thisapp --environment lab

create-simplebackend:
	bin/stack -create --template simplebackend --domain-name thisapp-lab
