version: '3'
services:
    thisapi:
        build:
            context: ../backend
            dockerfile: Dockerfile
        networks:
            - internal
        ports:
            - 5000:5000

    thisapp:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        networks:
            - internal
            - external
        ports:
            - 8080:80
            - 8443:443
    redis:
        image: redis:alpine
        networks:
            - internal
            - external
        ports:
            - 6379:6379

networks:
    internal:
    external:
        # Probably some stuff to give it external access.

